### PR TITLE
Using both produces and response

### LINKED ISSUE #187: [Feature Request] Support content_type when using doc.response() and respect doc.produces() when using both
The method `doc.response()` does not accept `content_type` and its default value is `application/json`, can we add `content_type` to it?

When using both `doc.produces()` and `doc.response()`, `doc.produces()` will be ignored, I suggest we either remove it to avoid confusion or respect it when using both.

### PR DESCRIPTION
**Pull request by denisovkv**
Closes #187

### CODE REVIEW

**Comment by artcg** [comment]
Nice job, looks like you can also remove the block of code

```
if len(route_spec.response) == 0:
                responses["200"] = {
                    "schema": serialize_schema(route_spec.produces.field) if route_spec.produces else None,
                    "description": route_spec.produces.description if route_spec.produces else None,
                }
```

As the code you wrote replaces that

**Comment by denisovkv** [comment]
@artcg forgot to push, thank you :)

**Review by artcg — DISMISSED** [review]

**Comment by ahopkins** [comment]
@denisovkv Can you take a look at this conflict?

**Comment by denisovkv** [comment]
@ahopkins Done

**Review by ahopkins — APPROVED** [review]

**Pull request merged**
