### PR TITLE
feat: inital new doc supporting oas2 and oas3

### PR DESCRIPTION
**Pull request by astagi**
This is still a WIP

### CODE REVIEW

**Comment by artcg** [comment]
Looks great so far :)

**Comment by artcg** [comment]
👍  btw dont worry about documenting the "class based view" since that feature of sanic is being phased out a bit ...

**Comment by astagi** [comment]
@artcg doc is ready for review. I also add a commit to support multiple schemas, I'll open a new PR to support multiple servers for OAS3 soon. I made descriptive commit messages, I think is better to merge PR without squashing them in case you want to easily revert code fixes.

No problem for class-based views, it didn't get me so much time. In case we may remove it in the future.

**Review by artcg — APPROVED** [review]

**Comment by artcg** [comment]
Awesome :) I was thinking about something like that with the server also ...

**Pull request merged**
