### PR TITLE
Path parameter description

### LINKED ISSUE #188: [Feature Request] Add description to path parameters
I've started using sanic-openapi to document our APIs and I'm currently struggling to add a description to a route's path parameter. Since there's no documentation on how to do this, I decided to open this issue to see if I'm just missing something or if this is a legitimate feature request.

For example, I have a route that looks like this:
```python
bp = Blueprint('foo', url_prefix='/foo')

@bp.route('/<foo_id>/bar, methods=['GET', 'OPTIONS'])
async def get_foo_bar_by_id(request, foo_id):
    return {'bar': 'something', 'foo': foo_id}
```

The Swagger page will automatically generate a parameter for this endpoint with the correct name, but no description, as you can see in the attached screenshot.

Screenshot 2020-08-11 at 14 54 18

I've tried adding the following annotation to the endpoint:
```python
@doc.consumes(doc.String(description='The description', name='foo_id'), location='path', required=True)
```

However, the annotation above changes nothing. The automatically created parameter is still being shown with an empty description.

If this feature doesn't currently exist, I'd love to have a way to override the path parameters default description, as I want to explain exactly what should go in there. Currently, my workaround is to simply add that explanation to the description.

### PR DESCRIPTION
**Pull request by denisovkv**
Closes #188

@chenjr0719 Hello! Answering on feature request #188 May be defining path parameters in consume decorator instead of getting from route parameters is a better idea? Explicit is better than implicit :)

### CODE REVIEW

**Comment by opensorceror** [comment]
bump

**Comment by artcg** [comment]
I like the idea but I think the current method of automatically parsing the path parameters is too valuable to lose,

If this PR was changed to make the manually decorated parameter annotation update the default value with the description instead of overwrite it I think it could be useful, but since the PR is half a year old I think it would be better to close this PR  @ahopkins

**Comment by denisovkv** [comment]
@artcg
Thank you for a reasonable comment!

I just added some improvements. They would save current path param autodetect and override it with decorator.
What do you think?

**Comment by artcg** [comment]
Cool thanks for the quick change :) I thought this was inactive but great that we can still add it

I think that the `route_param = {}` addition at L165 is not necessary, so might be good to take that out, but generally this looks good and with this change, I would recommend to @ahopkins that this PR be merged when he has time to go through them ...

**Review by artcg — APPROVED** [review]

**Review by ahopkins — APPROVED** [review]

**Pull request merged**
