### PR TITLE
Add handling for decoration of bounded method.

### PR DESCRIPTION
**Pull request by iAndriy**
That PR address following documentation generation use case:

```
class_instance = view_class.as_view()
app.add_route(class_instance.some_method, '/some_other_url/') 
app.add_route(class_instance, '/some_url/')
```

### CODE REVIEW

**Comment by iAndriy** [comment]
@chenjr0719 @ahopkins What is the process of version bump (hasn't found anything about that in CONTRIBUTING.md) ?

**Comment by ahopkins** [comment]
Not sure I understand the question. No need for you to change the version. That will be handled when the next release is prepared.

**Comment by iAndriy** [comment]
@ahopkins ok, that's why I've asked, wasn't clear to me :) Shall I assign reviewer to PR ?

**Comment by iAndriy** [comment]
@ahopkins How often release occurs ? Is that PR gone be in next one ?

**Comment by ahopkins** [comment]
@chenjr0719?

**Comment by iAndriy** [comment]
@ahopkins @chenjr0719 Does that project active ?

**Comment by ahopkins** [comment]
I do not maintain this. I help the people that do when they need it since I hold the keys to the organization. If you are interested in helping out please let me know.

**Comment by iAndriy** [comment]
> I do not maintain this. I help the people that do when they need it since I hold the keys to the organization. If you are interested in helping out please let me know.

@ahopkins I don't mind in helping out with the maintenance.

**Comment by ahopkins** [comment]
> > I do not maintain this. I help the people that do when they need it since I hold the keys to the organization. If you are interested in helping out please let me know.
> 
> @ahopkins I don't mind in helping out with the maintenance.

If you are still interested, please send me a message on the forums:

https://community.sanicframework.org/

**Comment by ahopkins** [comment]
Conflict here need resolving.

**Comment by artcg** [comment]
Cant re-create, 

```python
from sanic.views import HTTPMethodView

class FooBar(HTTPMethodView):
    async def get(self, request):
        pass

    async def post(self, request):
        pass

    async def put(self, request):
        pass

class_instance = FooBar.as_view()
app.add_route(class_instance, '/some_url/')

app.run()
```

Works fine for me, can you please add a minimal example of what this fixes?

**Pull request closed without merging**
